In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/data/insurance.csv")
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.shape

(1338, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
gender      1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [5]:
pd.get_dummies(df, drop_first=True).head()

age     bmi  children      charges  gender_male  smoker_yes  \
0   19  27.900         0  16884.92400            0           1   
1   18  33.770         1   1725.55230            1           0   
2   28  33.000         3   4449.46200            1           0   
3   33  22.705         0  21984.47061            1           0   
4   32  28.880         0   3866.85520            1           0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

In [6]:
from sklearn import model_selection
import numpy as np

In [44]:
target = "charges"
X = df.drop(columns=[target])
X = pd.get_dummies(X, drop_first=True)
features = X.columns
y = df[target]

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,
                           test_size = 0.3, random_state = 1)

In [8]:
X_train.shape, X_test.shape

((936, 8), (402, 8))

In [9]:
936/len(X)

0.6995515695067265

In [10]:
np.random.seed(1)
np.random.randn(5)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763])

In [11]:
from sklearn import preprocessing

In [12]:
scaler = preprocessing.StandardScaler()
X_train_std = scaler.fit_transform(X_train.astype("float"))

In [13]:
X_train_std

array([[ 0.79715222, -0.70211414, -0.90400228, ...,  1.78810218,
        -0.60038747, -0.58722022],
       [-1.27108519, -0.70375759, -0.08567913, ..., -0.55925216,
        -0.60038747,  1.70293864],
       [-0.98581107, -0.73333977, -0.90400228, ..., -0.55925216,
        -0.60038747, -0.58722022],
       ...,
       [ 0.86847075,  0.70303946,  0.73264401, ..., -0.55925216,
        -0.60038747, -0.58722022],
       [ 0.0839669 , -1.39072157,  0.73264401, ..., -0.55925216,
         1.66559105, -0.58722022],
       [ 1.29638193, -0.4506656 , -0.08567913, ..., -0.55925216,
         1.66559105, -0.58722022]])

In [45]:
pd.DataFrame(X_train_std, columns=features).sample(10)

age       bmi  children  gender_male  smoker_yes  region_northwest  \
926 -0.771855  0.031688 -0.904002     0.976766   -0.509664          1.788102   
86  -1.199767  1.449168 -0.904002     0.976766   -0.509664         -0.559252   
439 -0.843174 -2.091655  0.732644    -1.023787    1.962076         -0.559252   
283 -1.342404  0.127830 -0.904002    -1.023787   -0.509664         -0.559252   
363  0.725834 -0.577212 -0.904002    -1.023787   -0.509664         -0.559252   
234  1.439019  0.109752 -0.904002    -1.023787   -0.509664          1.788102   
412 -0.700537  0.437622  0.732644     0.976766   -0.509664          1.788102   
161 -1.485041 -2.419524 -0.904002     0.976766   -0.509664         -0.559252   
352  1.652975 -1.525485 -0.904002     0.976766   -0.509664         -0.559252   
763 -0.129989 -0.436696  0.732644     0.976766   -0.509664          1.788102   

     region_southeast  region_southwest  
926         -0.600387         -0.587220  
86          -0.600387          1.702939  
439         -0.600387         -0.587220  
283          1.665591         -0.587220  
363          1.665591         -0.587220  
234         -0.600387         -0.587220  
412         -0.600387         -0.587220  
161         -0.600387         -0.587220  
352         -0.600387          1.702939  
763         -0.600387         -0.587220

In [15]:
pd.DataFrame(X_train_std).describe()

0             1             2             3             4  \
count  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02   
mean  -1.791065e-16 -4.635418e-16 -2.910332e-16  1.767342e-17  8.979047e-17   
std    1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00   
min   -1.485041e+00 -2.419524e+00 -9.040023e-01 -1.023787e+00 -5.096643e-01   
25%   -9.144925e-01 -7.247116e-01 -9.040023e-01 -1.023787e+00 -5.096643e-01   
50%   -5.867016e-02 -3.076297e-02 -8.567913e-02  9.767656e-01 -5.096643e-01   
75%    8.684707e-01  6.631857e-01  7.326440e-01  9.767656e-01 -5.096643e-01   
max    1.795612e+00  3.689196e+00  3.187613e+00  9.767656e-01  1.962076e+00   

                  5             6             7  
count  9.360000e+02  9.360000e+02  9.360000e+02  
mean  -1.088873e-16  4.886879e-17 -2.372271e-17  
std    1.000535e+00  1.000535e+00  1.000535e+00  
min   -5.592522e-01 -6.003875e-01 -5.872202e-01  
25%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
50%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
75%   -5.592522e-01  1.665591e+00  1.702939e+00  
max    1.788102e+00  1.665591e+00  1.702939e+00

In [16]:
X_test_std = scaler.transform(X_test.astype("float"))

In [17]:
from sklearn import linear_model

In [18]:
est = linear_model.LinearRegression()
est.fit(X_train_std, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
y_train_pred = est.predict(X_train_std)
y_test_pred = est.predict(X_test_std)

In [20]:
train_error = (y_train - y_train_pred)

In [21]:
sse = np.sum(train_error ** 2)
sse

34142276155.204025

In [22]:
sst = np.sum((y_train - y_train.mean()) ** 2)
sst

139103996336.147

In [23]:
sse/sst

0.2454442507366839

In [24]:
r2 = 1 - sse/sst # Measure of goodness of the model, best value of R2 is 1
r2

0.7545557492633161

In [25]:
# R2 is negative, the model is not useful.

In [26]:
from sklearn import metrics

In [27]:
metrics.r2_score(y_train, y_train_pred)

0.7545557492633161

In [28]:
metrics.r2_score(y_test, y_test_pred)

0.7405989316927211

In [29]:
from sklearn import pipeline

In [30]:
target = "charges"
X = df.drop(columns=[target])
X = pd.get_dummies(X, drop_first=True).values.astype("float")
y = df[target]

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,
                           test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
	("scaler", preprocessing.StandardScaler()),
	("est", linear_model.LinearRegression())
])


pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("training r2", metrics.r2_score(y_train, y_train_pred))
print("test r2", metrics.r2_score(y_test, y_test_pred))

print("training rmse:", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("test rmse:", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))


training r2 0.7545557492633161
test r2 0.7405989316927208
training rmse: 6039.6018713245385
test rmse: 6063.122656850453


In [31]:
mse = np.mean((y_train - y_train_pred) ** 2)

In [32]:
rmse = np.sqrt(mse)

In [33]:
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [34]:
target = "charges"
X = df.drop(columns=[target])
#X["age_high"] = np.where(df.age>60, 1, 0)
#X["high_bmi"] = np.where(df.bmi>30, 1, 0)
X = pd.get_dummies(X, drop_first=True)
columns = X.columns
X = X.values.astype("float")
y = np.log(df[target])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,
                           test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=1, include_bias=False)),
	("scaler", preprocessing.StandardScaler()),
	("est", linear_model.LinearRegression())
])


pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("training r2", metrics.r2_score(y_train, y_train_pred))
print("test r2", metrics.r2_score(y_test, y_test_pred))

print("training rmse:", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("test rmse:", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))


training r2 0.7589104330619343
test r2 0.78742951961976
training rmse: 0.45174290241037973
test rmse: 0.4228608853190619


In [35]:
est = pipe.steps[-1][-1]
est.coef_

array([ 0.47147365,  0.08158994,  0.115362  , -0.04554678,  0.62975311,
       -0.02392739, -0.07216256, -0.06006463])

In [36]:
pd.DataFrame({"feature": columns, "coefficient": est.coef_})

feature  coefficient
0               age     0.471474
1               bmi     0.081590
2          children     0.115362
3       gender_male    -0.045547
4        smoker_yes     0.629753
5  region_northwest    -0.023927
6  region_southeast    -0.072163
7  region_southwest    -0.060065

In [37]:
est.intercept_

9.095336942703502

In [38]:
target = "charges"
X = df.drop(columns=[target])
X["age_high"] = np.where(df.age>60, 1, 0)
X["high_bmi"] = np.where(df.bmi>30, 1, 0)
X = pd.get_dummies(X, drop_first=True)
columns = X.columns
X = X.values.astype("float")
y = np.log(df[target])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,
                           test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=2, include_bias=False)),
	("scaler", preprocessing.StandardScaler()),
	("est", linear_model.LinearRegression())
])


pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("training r2", metrics.r2_score(y_train, y_train_pred))
print("test r2", metrics.r2_score(y_test, y_test_pred))

print("training rmse:", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("test rmse:", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))


training r2 0.834788529494612
test r2 0.8705884967625366
training rmse: 0.37395748281705865
test rmse: 0.3299381072855681


In [39]:
est = pipe.steps[-1][-1]
est.coef_

array([ 6.95782168e-01,  2.99070081e-02,  4.08311483e-01, -7.21871116e+11,
       -6.45231393e+11, -2.02784693e+12, -2.75499672e+12,  3.58978197e+12,
       -4.63246052e+12,  2.46814498e+12, -2.59948730e-01,  6.83593750e-02,
       -1.59729004e-01, -8.94241333e-01, -9.86328125e-02,  1.25488281e-01,
       -5.66162109e-01,  9.35058594e-02,  2.12890625e-01,  2.16796875e-01,
        7.99560547e-02, -7.69653320e-02, -2.62519836e-01, -1.72515869e-01,
        6.70776367e-02,  2.07275391e-01, -1.70410156e-01, -4.09423828e-01,
       -7.81250000e-02, -6.76879883e-02,  2.34375000e-02, -1.56860352e-02,
        6.22558594e-03, -1.01684570e-01,  2.80761719e-02,  2.31323242e-02,
        0.00000000e+00,  7.21871116e+11,  5.48858643e-02, -6.08825684e-03,
        4.39453125e-03, -1.67236328e-02, -6.10351562e-03, -2.11181641e-02,
        6.45231393e+11, -3.66210938e-04,  1.49414062e-01,  1.22070312e-03,
        8.12988281e-02, -2.29492188e-02,  2.02784693e+12,  2.64892578e-02,
       -2.44140625e-04, -

In [40]:
a = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [-2, 1, 2],
    [3, 2, 1]
])
a

array([[ 1,  1,  1],
       [ 1,  2,  3],
       [-2,  1,  2],
       [ 3,  2,  1]])

In [41]:
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(a)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  1.,  2.,  3.,  4.,  6.,  9.],
       [-2.,  1.,  2.,  4., -2., -4.,  1.,  2.,  4.],
       [ 3.,  2.,  1.,  9.,  6.,  3.,  4.,  2.,  1.]])

In [42]:
a = np.random.random((4, 1000))
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(a).shape

(4, 501500)

In [51]:
target = "charges"
X = df.drop(columns=[target])
X["age_high"] = np.where(df.age>60, 1, 0)
X["high_bmi"] = np.where(df.bmi>30, 1, 0)
X = pd.get_dummies(X, drop_first=True)
columns = X.columns
X = X.values.astype("float")
y = np.log(df[target])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,
                           test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=2, include_bias=False)),
	("scaler", preprocessing.StandardScaler()),
	("est", linear_model.Lasso(alpha=0.1, random_state=1))
])


pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("training r2", metrics.r2_score(y_train, y_train_pred))
print("test r2", metrics.r2_score(y_test, y_test_pred))

print("training rmse:", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("test rmse:", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
est = pipe.steps[-1][-1]

est.coef_



training r2 0.7324281490897704
test r2 0.7498265539662363
training rmse: 0.47590727183370596
test rmse: 0.45874003473531594


array([ 0.37779439,  0.        ,  0.0174025 ,  0.        ,  0.        ,
       -0.        ,  0.10091026,  0.        , -0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        0.4064069 ,  0.        , -0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        ,  0.        ,  0.        ,
       -0.        ,  0.04071257,  0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        , -0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        ,  0.        , -0.        ])