In [1]:
import numpy as np

In [2]:
a = np.array([3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a = np.array([3.0, 4.9, 5.8])
a.dtype

dtype('float64')

In [7]:
a.shape

(3,)

In [8]:
v = (2, 3)
v

(2, 3)

In [9]:
type(v)

tuple

In [10]:
v = (2)
v

2

In [11]:
type(v)

int

In [12]:
v = (2, )

In [13]:
v

(2,)

In [14]:
type(v)

tuple

In [15]:
a = np.array([
    [2,3,4],
    [5, 0, -1]
])

a

array([[ 2,  3,  4],
       [ 5,  0, -1]])

In [16]:
a.shape

(2, 3)

In [17]:
np.sum(a)

13

In [18]:
np.sum(a, axis=0)

array([7, 3, 3])

In [19]:
np.sum(a, axis=1)

array([9, 4])

In [21]:
a = np.random.ranf(5)
a

array([0.03347107, 0.30470157, 0.14247519, 0.08019544, 0.89738764])

In [22]:
a = np.random.ranf([5, 4])
a

array([[0.40503926, 0.57972869, 0.30018275, 0.73421501],
       [0.19601972, 0.1139859 , 0.43039953, 0.12215737],
       [0.12917518, 0.98898938, 0.25095177, 0.59738002],
       [0.86325905, 0.04375335, 0.95799531, 0.65714683],
       [0.41737497, 0.6730023 , 0.07774596, 0.59644279]])

In [24]:
a = (np.random.ranf(5) * 10).astype(np.int32)
a

array([4, 8, 7, 9, 0], dtype=int32)

In [25]:
np.product(a)

0

In [26]:
np.mean(a)

5.6

In [27]:
np.var(a)

10.64

In [28]:
np.std(a)

3.2619012860600183

In [29]:
np.sum((a - np.mean(a)) ** 2)/len(a)

10.64

In [30]:
np.sqrt(10.64)

3.2619012860600183

In [31]:
a 

array([4, 8, 7, 9, 0], dtype=int32)

In [32]:
a ** 2

array([16, 64, 49, 81,  0], dtype=int32)

In [33]:
np.sqrt(a)

array([2.        , 2.82842712, 2.64575131, 3.        , 0.        ])

In [34]:
a + 10

array([14, 18, 17, 19, 10], dtype=int32)