In [41]:
import numpy as np
import tensorflow as tf
import pandas as pd
import keras
from time import time

In [5]:
sigmoid = lambda x: 1 / (1 + np.exp(-x))
X_data = np.random.ranf((100, 2))
W_true = np.array([1.4, -6.7])
y_data = np.where(sigmoid(np.dot(X_data, W_true) + 2.4) > 0.5, 1, 0)
y_data

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1])

In [7]:
pd.Series(y_data).value_counts()

1    52
0    48
dtype: int64

In [9]:
X = tf.placeholder("float32", (None, 2))
y = tf.placeholder("int32", (None,))
W = tf.Variable(tf.truncated_normal((2, 1)))
b = tf.Variable(0.0)


dW = tf.gradients()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    W_ = sess.run(W)
    print(W_)

[[-0.8651776]
 [ 0.9817738]]


In [36]:
from sklearn import preprocessing, model_selection
df = pd.read_csv("/data/iris.csv")
df.head()
X = df.iloc[:, 1:-1].values
X = preprocessing.StandardScaler().fit_transform(X)
y = preprocessing.LabelEncoder().fit_transform(df.Species)
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.2, random_state = 1)

In [24]:
pd.Series(y).value_counts()

2    50
1    50
0    50
dtype: int64

In [25]:
X.shape

(150, 4)

In [27]:
keras.utils.to_categorical(y)[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [63]:
tf.set_random_seed(1)
np.random.seed(1)

adam = keras.optimizers.Adam(lr=0.1, decay=0.01)

tensorboard = keras.callbacks.TensorBoard(log_dir="/tmp/tf/tensorboard/%d" % time())
model = keras.Sequential()
model.add(keras.layers.InputLayer((4,)))
model.add(keras.layers.Dense(3, activation="relu"))
#model.add(keras.layers.Dense(5, activation="relu"))
model.add(keras.layers.Dense(3, activation="softmax"))
model.compile(loss="categorical_crossentropy", optimizer=adam, metrics=["acc"])
model.summary()

model.fit(X_train, keras.utils.to_categorical(y_train)
          , batch_size = 200
          , callbacks=[tensorboard]
          , validation_data = (X_test, keras.utils.to_categorical(y_test)) 
          , epochs=500
          , verbose=0)
model.evaluate(X_test, keras.utils.to_categorical(y_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_38 (InputLayer)        (None, 4)                 0         
_________________________________________________________________
dense_79 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_80 (Dense)             (None, 3)                 12        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________
30/30 [==============================] - 0s 33us/step


[0.023893708363175392, 1.0]