In [1]:
import pandas as pd
import numpy as np
from sklearn import *

import matplotlib.pyplot as plt

%matplotlib inline


In [2]:
df = pd.read_csv("/data/credit-default.csv")
df.head()

checking_balance  months_loan_duration credit_history    purpose  amount  \
0           < 0 DM                     6       critical   radio/tv    1169   
1       1 - 200 DM                    48         repaid   radio/tv    5951   
2          unknown                    12       critical  education    2096   
3           < 0 DM                    42         repaid  furniture    7882   
4           < 0 DM                    24        delayed  car (new)    4870   

  savings_balance employment_length  installment_rate personal_status  \
0         unknown           > 7 yrs                 4     single male   
1        < 100 DM         1 - 4 yrs                 2          female   
2        < 100 DM         4 - 7 yrs                 2     single male   
3        < 100 DM         4 - 7 yrs                 2     single male   
4        < 100 DM         1 - 4 yrs                 3     single male   

  other_debtors  ...                  property age  installment_plan  \
0          none  ...               real estate  67              none   
1          none  ...               real estate  22              none   
2          none  ...               real estate  49              none   
3     guarantor  ...  building society savings  45              none   
4          none  ...              unknown/none  53              none   

    housing existing_credits  default  dependents  telephone foreign_worker  \
0       own                2        1           1        yes            yes   
1       own                1        2           1       none            yes   
2       own                1        1           2       none            yes   
3  for free                1        1           2       none            yes   
4  for free                2        2           2       none            yes   

                  job  
0    skilled employee  
1    skilled employee  
2  unskilled resident  
3    skilled employee  
4    skilled employee  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
checking_balance        1000 non-null object
months_loan_duration    1000 non-null int64
credit_history          1000 non-null object
purpose                 1000 non-null object
amount                  1000 non-null int64
savings_balance         1000 non-null object
employment_length       1000 non-null object
installment_rate        1000 non-null int64
personal_status         1000 non-null object
other_debtors           1000 non-null object
residence_history       1000 non-null int64
property                1000 non-null object
age                     1000 non-null int64
installment_plan        1000 non-null object
housing                 1000 non-null object
existing_credits        1000 non-null int64
default                 1000 non-null int64
dependents              1000 non-null int64
telephone               1000 non-null object
foreign_worker          1000 non-null object
jo

In [4]:
df.default.value_counts()

1    700
2    300
Name: default, dtype: int64

In [5]:
target = "default"
y = np.where(df[target] == 2, 1, 0)
y

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [20]:
target = "default"
y = np.where(df[target] == 2, 1, 0)

X = df.drop(columns=[target])
X = pd.get_dummies(X)
features = X.columns

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values * 1.0, y
                , test_size = 0.3, random_state = 1)


pipe = pipeline.Pipeline([
    #("scaler", preprocessing.StandardScaler()),
    ("est", tree.DecisionTreeClassifier(max_depth = 6, criterion = "entropy",
                                        max_leaf_nodes = 10, min_samples_leaf = 15))
])

pipe.fit(X_train, y_train)


y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)


print("train accuracy", metrics.accuracy_score(y_train, y_train_pred))
print("test accuracy", metrics.accuracy_score(y_test, y_test_pred))

print("train precision", metrics.precision_score(y_train, y_train_pred))
print("test precision", metrics.precision_score(y_test, y_test_pred))

print("train recall", metrics.recall_score(y_train, y_train_pred))
print("test recall", metrics.recall_score(y_test, y_test_pred))

metrics.confusion_matrix(y_test, y_test_pred)

train accuracy 0.7385714285714285
test accuracy 0.7433333333333333
train precision 0.628099173553719
test precision 0.5957446808510638
train recall 0.35514018691588783
test recall 0.32558139534883723


array([[195,  19],
       [ 58,  28]])

In [21]:
est = pipe.steps[-1][-1]
est

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
            max_features=None, max_leaf_nodes=10,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=15, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
from sklearn.tree import export_graphviz
export_graphviz(est, out_file = "tree.dot", feature_names = X.columns, filled=True)
!dot -Tpng tree.dot -o tree.png

In [25]:
summary = pd.DataFrame({"feaeture": features, "importance": est.feature_importances_}) 
summary.sort_values("importance", ascending = False)

feaeture  importance
10               checking_balance_unknown    0.389270
11                credit_history_critical    0.158705
0                    months_loan_duration    0.108080
41                other_debtors_guarantor    0.092242
33            employment_length_4 - 7 yrs    0.078781
48                  installment_plan_none    0.062172
17                      purpose_car (new)    0.060822
28               savings_balance_< 100 DM    0.049928
37                 personal_status_female    0.000000
38           personal_status_married male    0.000000
39            personal_status_single male    0.000000
40             other_debtors_co-applicant    0.000000
45                   property_real estate    0.000000
36          personal_status_divorced male    0.000000
35           employment_length_unemployed    0.000000
42                     other_debtors_none    0.000000
43      property_building society savings    0.000000
44                         property_other    0.000000
47                  installment_plan_bank    0.000000
46                  property_unknown/none    0.000000
49                installment_plan_stores    0.000000
50                       housing_for free    0.000000
51                            housing_own    0.000000
52                           housing_rent    0.000000
53                         telephone_none    0.000000
54                          telephone_yes    0.000000
55                      foreign_worker_no    0.000000
56                     foreign_worker_yes    0.000000
57            job_mangement self-employed    0.000000
58                   job_skilled employee    0.000000
..                                    ...         ...
34              employment_length_> 7 yrs    0.000000
30                savings_balance_unknown    0.000000
32            employment_length_1 - 4 yrs    0.000000
31            employment_length_0 - 1 yrs    0.000000
2                        installment_rate    0.000000
3                       residence_history    0.000000
4                                     age    0.000000
5                        existing_credits    0.000000
6                              dependents    0.000000
7             checking_balance_1 - 200 DM    0.000000
8                 checking_balance_< 0 DM    0.000000
9               checking_balance_> 200 DM    0.000000
12                 credit_history_delayed    0.000000
13            credit_history_fully repaid    0.000000
14  credit_history_fully repaid this bank    0.000000
15                  credit_history_repaid    0.000000
16                       purpose_business    0.000000
18                     purpose_car (used)    0.000000
19            purpose_domestic appliances    0.000000
20                      purpose_education    0.000000
21                      purpose_furniture    0.000000
22                         purpose_others    0.000000
23                       purpose_radio/tv    0.000000
24                        purpose_repairs    0.000000
25                     purpose_retraining    0.000000
26           savings_balance_101 - 500 DM    0.000000
27          savings_balance_501 - 1000 DM    0.000000
29              savings_balance_> 1000 DM    0.000000
1                                  amount    0.000000
60                 job_unskilled resident    0.000000

[61 rows x 2 columns]

In [26]:
summary.importance.sum()

0.9999999999999999

In [28]:
target = "default"
y = np.where(df[target] == 2, 1, 0)

X = df.drop(columns=[target])
X = pd.get_dummies(X)
features = X.columns

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values * 1.0, y
                , test_size = 0.3, random_state = 1)


pipe = pipeline.Pipeline([
    #("scaler", preprocessing.StandardScaler()),
    ("est", ensemble.RandomForestClassifier(n_estimators= 20, max_features = 0.7, max_depth = 6, 
                                        criterion = "entropy",
                                        max_leaf_nodes = 10, min_samples_leaf = 15))
])

pipe.fit(X_train, y_train)


y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

est = pipe.steps[-1][-1]


print("train accuracy", metrics.accuracy_score(y_train, y_train_pred))
print("test accuracy", metrics.accuracy_score(y_test, y_test_pred))

print("train precision", metrics.precision_score(y_train, y_train_pred))
print("test precision", metrics.precision_score(y_test, y_test_pred))

print("train recall", metrics.recall_score(y_train, y_train_pred))
print("test recall", metrics.recall_score(y_test, y_test_pred))

metrics.confusion_matrix(y_test, y_test_pred)

train accuracy 0.7928571428571428
test accuracy 0.7466666666666667
train precision 0.7518248175182481
test precision 0.625
train recall 0.48130841121495327
test recall 0.29069767441860467


array([[199,  15],
       [ 61,  25]])

In [29]:
est.feature_importances_

array([0.09570658, 0.11795736, 0.02994001, 0.01101347, 0.0602965 ,
       0.00690716, 0.        , 0.01984002, 0.09447485, 0.        ,
       0.23853731, 0.10710685, 0.00380472, 0.01005263, 0.        ,
       0.00601608, 0.00737333, 0.0150879 , 0.        , 0.        ,
       0.        , 0.0080841 , 0.        , 0.00548312, 0.        ,
       0.        , 0.        , 0.        , 0.03048418, 0.        ,
       0.01991822, 0.00575904, 0.        , 0.02333629, 0.00341704,
       0.        , 0.        , 0.        , 0.        , 0.0111689 ,
       0.        , 0.00565492, 0.00905631, 0.        , 0.00319446,
       0.01162028, 0.        , 0.00435435, 0.03138596, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00296804, 0.        ,
       0.        ])

In [30]:
est.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
             max_features=0.7, max_leaf_nodes=10, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=15,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=441842002, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
             max_features=0.7, max_leaf_nodes=10, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=15,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=1800940011, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
             max_features=0.7, max_leaf_nodes=10, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=15,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, 