In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/data/insurance.csv")
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [24]:
target = "charges"
X = df.drop(columns=[target]) 
# Feature matrix, does not contain the target var

y = df[target] 
# label - dependent variable

In [27]:
X_dummy = pd.get_dummies(X, drop_first=True) 
# One hot encoding for categorical variables
X_dummy.head()

age     bmi  children  gender_male  smoker_yes  region_northwest  \
0   19  27.900         0            0           1                 0   
1   18  33.770         1            1           0                 0   
2   28  33.000         3            1           0                 0   
3   33  22.705         0            1           0                 1   
4   32  28.880         0            1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

z_score = (x - x.mean())/x.std(), for every column x independently

Z_score gives 0 mean and 1 standard deviation for each column

For some algorithm, z-scoring the features is mandatory (KMean, PCA)
For some, it is recommended - gradient descent 
For some, it is not required (decision tree, random forest)

Main motivation for z-scoring is to speed up the computation during training.


In [7]:
import numpy as np

In [104]:
x = np.array([1000, 10000, 20000, 1000000])
x

array([   1000,   10000,   20000, 1000000])

In [105]:
np.mean(x)

257750.0

In [11]:
x - 4.6

array([-0.6, -2.6, -4.6,  3.4,  4.4])

In [12]:
(x - 4.6) ** 2

array([ 0.36,  6.76, 21.16, 11.56, 19.36])

In [14]:
var = ((x - 4.6) ** 2).mean()
var

11.84

In [16]:
std = np.sqrt(var)
std

3.4409301068170506

In [17]:
np.std(x)

3.4409301068170506

In [106]:
z = (x - x.mean())/np.std(x)
z

array([-0.59905607, -0.57805703, -0.55472475,  1.73183785])

In [107]:
np.mean(z)

-5.551115123125783e-17

In [108]:
np.std(z)

0.9999999999999999

In [ ]:
sqrt(((x - x.mean()) ** 2).mean())

In [22]:
from sklearn import preprocessing

In [33]:
scaler = preprocessing.StandardScaler()
scaler.fit(X_dummy)
X_std = pd.DataFrame(scaler.transform(X_dummy))
X_std.describe()

0             1             2             3             4  \
count  1.338000e+03  1.338000e+03  1.338000e+03  1.338000e+03  1.338000e+03   
mean  -1.853691e-16 -1.869041e-16  2.721623e-17 -7.567439e-17  2.142448e-16   
std    1.000374e+00  1.000374e+00  1.000374e+00  1.000374e+00  1.000374e+00   
min   -1.509965e+00 -2.412011e+00 -9.086137e-01 -1.010519e+00 -5.074631e-01   
25%   -8.691547e-01 -7.164063e-01 -9.086137e-01 -1.010519e+00 -5.074631e-01   
50%   -1.474046e-02 -4.320880e-02 -7.876719e-02  9.895908e-01 -5.074631e-01   
75%    8.396738e-01  6.611572e-01  7.510793e-01  9.895908e-01 -5.074631e-01   
max    1.765289e+00  3.685522e+00  3.240619e+00  9.895908e-01  1.970587e+00   

                  5             6             7  
count  1.338000e+03  1.338000e+03  1.338000e+03  
mean  -2.846087e-16  1.186561e-16  1.481127e-16  
std    1.000374e+00  1.000374e+00  1.000374e+00  
min   -5.664179e-01 -6.113237e-01 -5.664179e-01  
25%   -5.664179e-01 -6.113237e-01 -5.664179e-01  
50%   -5.664179e-01 -6.113237e-01 -5.664179e-01  
75%   -5.664179e-01  1.635795e+00 -5.664179e-01  
max    1.765481e+00  1.635795e+00  1.765481e+00

In [34]:
from sklearn import model_selection

In [109]:
# splitting the data into training and test sets. 
# training dataset - we build the model
# testing dataset - we validate or test the model performance
X_train, X_test, y_train, y_test = \
    model_selection.train_test_split(X_dummy, y
                     , test_size = 0.3 # controls the size of test data ... it a number between 0 and 1
                     , random_state = 1 # reproduce the the randomness
                    )

In [71]:
X_train.shape

(936, 8)

In [72]:
X_test.shape

(402, 8)

In [74]:
936/len(X)

0.6995515695067265

In [70]:
np.random.seed(1)
np.random.random(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [75]:
scaler = preprocessing.StandardScaler()
scaler.fit(X_train) # calculates the mean and std for each column
X_train_std = scaler.transform(X_train) # calculates the z -score based 
X_test_std = scaler.transform(X_test) # calculates the z-score by re-using the mean and std of the training dataset

In [77]:
pd.DataFrame(X_train_std, columns=X_dummy.columns)

age       bmi  children  gender_male  smoker_yes  region_northwest  \
0    0.797152 -0.702114 -0.904002     0.976766   -0.509664          1.788102   
1   -1.271085 -0.703758 -0.085679    -1.023787   -0.509664         -0.559252   
2   -0.985811 -0.733340 -0.904002     0.976766   -0.509664         -0.559252   
3    0.797152 -0.414510  1.550967    -1.023787   -0.509664         -0.559252   
4    0.868471  1.482037 -0.085679     0.976766   -0.509664         -0.559252   
5   -0.985811  1.749098 -0.904002    -1.023787   -0.509664         -0.559252   
6   -0.843174  0.117970 -0.904002    -1.023787    1.962076         -0.559252   
7    1.724293 -0.608437 -0.904002    -1.023787    1.962076          1.788102   
8   -1.485041  0.525546 -0.904002    -1.023787   -0.509664         -0.559252   
9   -1.485041 -1.248563 -0.904002     0.976766   -0.509664         -0.559252   
10   1.367700  0.375170 -0.904002    -1.023787   -0.509664         -0.559252   
11  -0.700537 -1.451529 -0.904002    -1.023787    1.962076         -0.559252   
12   0.012648  1.827162 -0.904002    -1.023787   -0.509664         -0.559252   
13   1.153745  0.749878 -0.085679     0.976766   -0.509664         -0.559252   
14  -0.343944 -0.522978 -0.085679    -1.023787   -0.509664         -0.559252   
15  -1.342404 -1.426878 -0.085679     0.976766   -0.509664         -0.559252   
16   1.581656 -1.576432 -0.904002    -1.023787   -0.509664          1.788102   
17  -1.342404 -0.452309 -0.904002     0.976766   -0.509664         -0.559252   
18  -0.629218  1.339056 -0.085679     0.976766   -0.509664         -0.559252   
19   0.725834  1.013652 -0.904002     0.976766   -0.509664         -0.559252   
20  -0.914493 -0.311794 -0.904002    -1.023787   -0.509664         -0.559252   
21  -0.843174  0.676744 -0.085679    -1.023787   -0.509664         -0.559252   
22  -0.201307 -0.125262 -0.904002    -1.023787   -0.509664         -0.559252   
23  -1.342404 -1.029162 -0.904002    -1.023787    1.962076         -0.559252   
24  -1.413722 -1.788438 -0.904002     0.976766   -0.509664         -0.559252   
25  -1.485041 -0.858242 -0.904002     0.976766   -0.509664         -0.559252   
26   1.082426  0.843555  1.550967    -1.023787   -0.509664          1.788102   
27  -1.413722  0.297106 -0.904002    -1.023787    1.962076          1.788102   
28   0.297922 -1.734204  0.732644     0.976766    1.962076         -0.559252   
29  -1.199767  0.507468 -0.904002     0.976766   -0.509664         -0.559252   
..        ...       ...       ...          ...         ...               ...   
906  1.153745  0.742482 -0.904002    -1.023787    1.962076         -0.559252   
907 -0.914493  0.297106 -0.085679     0.976766   -0.509664         -0.559252   
908  1.082426  0.265881 -0.085679    -1.023787   -0.509664         -0.559252   
909  1.367700 -1.300332 -0.904002    -1.023787   -0.509664         -0.559252   
910 -1.057130  0.331619 -0.904002     0.976766    1.962076         -0.559252   
911 -0.985811  1.881396 -0.085679    -1.023787   -0.509664         -0.559252   
912  1.439019 -0.858242 -0.085679     0.976766   -0.509664         -0.559252   
913 -0.843174 -0.029941 -0.904002     0.976766   -0.509664         -0.559252   
914  1.795612 -0.835234  0.732644     0.976766   -0.509664         -0.559252   
915  1.652975  0.219042 -0.904002     0.976766    1.962076         -0.559252   
916  1.082426  0.579780  0.732644     0.976766    1.962076         -0.559252   
917  0.369241  0.272454 -0.085679    -1.023787   -0.509664         -0.559252   
918 -0.771855 -1.045596 -0.085679    -1.023787   -0.509664         -0.559252   
919 -0.415263 -0.998758  0.732644     0.976766   -0.509664          1.788102   
920  0.583197 -0.140053  1.550967     0.976766   -0.509664          1.788102   
921  0.012648 -0.124440 -0.085679     0.976766    1.962076         -0.559252   
922  0.440560 -0.052950 -0.904002     0.976766    1.962076         -0.559252   
923 -1.199767  0.234655 -0.904002     0.976766   -0.509664          1.788102   
924 -1.057

In [78]:
from sklearn import linear_model

In [80]:
lr = linear_model.LinearRegression() # helps find the theta values 
lr.fit(X_train_std, y_train) # Number of theta depends on the features in X

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [81]:
lr.coef_, lr.intercept_

(array([3528.98273114, 1961.65520818,  421.55016415, -141.35911014,
        9733.78688309, -129.54588605, -414.54148288, -379.09534369]),
 13276.698553898505)

In [82]:
pd.DataFrame({"feature": X_dummy.columns
            , "coeffficient": lr.coef_})

feature  coeffficient
0               age   3528.982731
1               bmi   1961.655208
2          children    421.550164
3       gender_male   -141.359110
4        smoker_yes   9733.786883
5  region_northwest   -129.545886
6  region_southeast   -414.541483
7  region_southwest   -379.095344

In [94]:
"y_hat = " + str(lr.intercept_) + " + " + " + ".join(["%f %s" % (theta, feature) 
          for feature, theta  in zip(X_dummy.columns, lr.coef_)])

'y_hat = 13276.698553898505 + 3528.982731 age + 1961.655208 bmi + 421.550164 children + -141.359110 gender_male + 9733.786883 smoker_yes + -129.545886 region_northwest + -414.541483 region_southeast + -379.095344 region_southwest'

In [95]:
lr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [97]:
y_train_pred = lr.predict(X_train_std)
y_test_pred = lr.predict(X_test_std)

In [100]:
result = pd.DataFrame({"actual": y_test, "prediction": y_test_pred})
result["error"] = result.actual - result.prediction
result.head()

actual    prediction        error
559    1646.4297   4610.315541 -2963.885841
1087  11353.2276  12887.893880 -1534.666280
1020   8798.5930  12573.948752 -3775.355752
460   10381.4787  13197.836626 -2816.357926
802    2103.0800    629.337182  1473.742818

In [101]:
SSE = (result.error ** 2).sum() # Squared sum of errors
SSE

14778105453.509336

In [102]:
MSE = SSE / len(result)
MSE

36761456.352013275

In [103]:
RMSE = np.sqrt(MSE)
RMSE

6063.122656850452

In [110]:
SST = ((y_test - y_train.mean()) ** 2).sum()

In [113]:
print(SSE/SST)

"""
What is expected?
A. Positive
B. < 1 
""";

0.2594002695488974


In [114]:
r2 = 1 - SSE/SST # Expected value range between 0 to 1. 1 is the best value.
r2 # Goodness of the model

0.7405997304511026

In [115]:
from sklearn import metrics

In [123]:
training_rmse = np.sqrt(metrics.mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
training_r2 = metrics.r2_score(y_train, y_train_pred)
test_r2 = metrics.r2_score(y_test, y_test_pred)

print("Training rmse: ", training_rmse)
print("Test rmse: ", test_rmse)
print("Training r2: ", training_r2)
print("Test r2: ", test_r2)

Training rmse:  6039.6018713245385
Test rmse:  6063.122656850452
Training r2:  0.7545557492633161
Test r2:  0.7405989316927211


In [124]:
target = "charges"
# Feature matrix, does not contain the target var
X = df.drop(columns=[target]) 

# label - dependent variable
y = df[target] 

# One hot encoding for categorical variables
X_dummy = pd.get_dummies(X, drop_first=True) 

# splitting the data into training and test sets. 
# training dataset - we build the model
# testing dataset - we validate or test the model performance
X_train, X_test, y_train, y_test = \
    model_selection.train_test_split(X_dummy, y
                     , test_size = 0.3 # controls the size of test data ... it a number between 0 and 1
                     , random_state = 1 # reproduce the the randomness
                    )
                    
scaler = preprocessing.StandardScaler()
scaler.fit(X_train) # calculates the mean and std for each column
X_train_std = scaler.transform(X_train) # calculates the z -score based 
X_test_std = scaler.transform(X_test) # calculates the z-score by re-using the mean and std of the training dataset


lr = linear_model.LinearRegression() # helps find the theta values 
lr.fit(X_train_std, y_train) # Number of theta depends on the features in X

# Calculate the prediction
y_train_pred = lr.predict(X_train_std)
y_test_pred = lr.predict(X_test_std)

training_rmse = np.sqrt(metrics.mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))
training_r2 = metrics.r2_score(y_train, y_train_pred)
test_r2 = metrics.r2_score(y_test, y_test_pred)

print("Training rmse: ", training_rmse)
print("Test rmse: ", test_rmse)
print("Training r2: ", training_r2)
print("Test r2: ", test_r2)




Training rmse:  6039.6018713245385
Test rmse:  6063.122656850452
Training r2:  0.7545557492633161
Test r2:  0.7405989316927211
