In [48]:
import pandas as pd

from sklearn import *
import numpy as np

pd.options.display.max_rows = 10
pd.options.display.max_columns = 1000

In [3]:
df = pd.read_csv("/data/kaggle/house-prices/data_combined_cleaned.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 80 columns):
Id               2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2919 non-null object
LotFrontage      2919 non-null float64
LotArea          2919 non-null int64
Street           2919 non-null object
Alley            2919 non-null object
LotShape         2919 non-null object
LandContour      2919 non-null object
LotConfig        2919 non-null object
LandSlope        2919 non-null object
Neighborhood     2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
BldgType         2919 non-null object
HouseStyle       2919 non-null object
OverallQual      2919 non-null int64
OverallCond      2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
RoofStyle        2919 non-null object
RoofMatl         2919 non-null object
Exterior1st      2919 non-null object
Exterior2nd      2919 non

In [8]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave  None      Reg   
1   2          20       RL         80.0     9600   Pave  None      Reg   
2   3          60       RL         68.0    11250   Pave  None      IR1   
3   4          70       RL         60.0     9550   Pave  None      IR1   
4   5          60       RL         84.0    14260   Pave  None      IR1   

  LandContour LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType  \
0         Lvl    Inside       Gtl      CollgCr       Norm       Norm     1Fam   
1         Lvl       FR2       Gtl      Veenker      Feedr       Norm     1Fam   
2         Lvl    Inside       Gtl      CollgCr       Norm       Norm     1Fam   
3         Lvl    Corner       Gtl      Crawfor       Norm       Norm     1Fam   
4         Lvl       FR2       Gtl      NoRidge       Norm       Norm     1Fam   

  HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle  \
0     2Story            7            5       2003          2003     Gable   
1     1Story            6            8       1976          1976     Gable   
2     2Story            7            5       2001          2002     Gable   
3     2Story            7            5       1915          1970     Gable   
4     2Story            8            5       2000          2000     Gable   

  RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond  \
0  CompShg     VinylSd     VinylSd    BrkFace       196.0        Gd        TA   
1  CompShg     MetalSd     MetalSd       None         0.0        TA        TA   
2  CompShg     VinylSd     VinylSd    BrkFace       162.0        Gd        TA   
3  CompShg     Wd Sdng     Wd Shng       None         0.0        TA        TA   
4  CompShg     VinylSd     VinylSd    BrkFace       350.0        Gd        TA   

  Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1  \
0      PConc       Gd       TA           No          GLQ       706.0   
1     CBlock       Gd       TA           Gd          ALQ       978.0   
2      PConc       Gd       TA           Mn          GLQ       486.0   
3     BrkTil       TA       Gd           No          ALQ       216.0   
4      PConc       Gd       TA           Av          GLQ       655.0   

  BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC  \
0          Unf         0.0      150.0        856.0    GasA        Ex   
1          Unf         0.0      284.0       1262.0    GasA        Ex   
2          Unf         0.0      434.0        920.0    GasA        Ex   
3          Unf         0.0      540.0        756.0    GasA        Gd   
4          Unf         0.0      490.0       1145.0    GasA        Ex   

  CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  \
0          Y      SBrkr       856       854             0       1710   
1          Y      SBrkr      1262         0             0       1262   
2          Y      SBrkr       920       866             0       1786   
3          Y      SBrkr       961       756             0       1717   
4          Y      SBrkr      1145      1053             0       2198   

   BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0           1.0           0.0         2         1             3             1   
1           0.0           1.0         2         0             3             1   
2           1.0           0.0         2         1             3             1   
3           1.0           0.0         1         0             3             1   
4           1.0           0.0         2         1             4             1   

  KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  \
0          Gd             8        Typ           0        None     Attchd   
1          TA             6        Typ           1          TA     Attchd   
2          Gd             6        Typ           1          TA     Attchd   
3          Gd             7

In [12]:
df = df[~df.SalesPrice.isnull()]
del df["Id"]

In [13]:
df.shape

(1460, 79)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 0 to 1459
Data columns (total 79 columns):
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1460 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1460 no

In [16]:
target = "SalesPrice" # name of the target variable
y = df[target] # label .. or the target 
X = df.copy() # features ... label is not included
del X[target]
X = pd.get_dummies(X, drop_first=True) # handle catergorical variables ... one hot encoding

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                            , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=5, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LinearRegression())
])
                                      
pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("Training mse:", metrics.mean_squared_error(y_train, y_train_pred),
     "\nTest mse:", metrics.mean_squared_error(y_test, y_test_pred), 
      "\nTraining r2:", metrics.r2_score(y_train, y_train_pred),
      "\nTest r2:", metrics.r2_score(y_test, y_test_pred))

Training mse: 394282456.5496736 
Test mse: 1.1245558927648565e+30 
Training r2: 0.933719292823807 
Test r2: -1.5749414565355304e+20


In [20]:
pipe.steps[-1][-1].coef_

array([ 3.31733827e+03,  2.78593369e+02,  8.34921880e+03,  7.42675815e+03,
        5.80147125e+03,  7.91868710e+03,  1.67617241e+03,  2.33783518e+03,
        2.45088881e+15,  8.72206877e+14,  2.32026401e+15, -2.37111201e+15,
        2.17526821e+15,  2.41216818e+15,  2.66377661e+14, -2.93658731e+15,
       -5.89609375e+02,  5.72353516e+02,  2.10209375e+03,  1.96148438e+03,
       -7.96625000e+02, -1.71589941e+03,  1.15440625e+03,  4.31864062e+03,
       -2.79220312e+03,  1.21589062e+03,  8.14250977e+03,  1.24915625e+03,
        4.51660156e+02,  7.08664062e+02,  8.51327148e+02,  1.75673438e+03,
        7.35770703e+03,  2.59715625e+03, -1.19405469e+03, -7.44000000e+02,
        8.42607812e+03,  4.14396875e+03,  1.49720938e+04,  1.39856562e+04,
       -5.64500000e+02, -1.40487500e+03,  2.66312500e+02,  5.83031250e+02,
        8.31859375e+02,  5.72453125e+02,  2.28537305e+03, -1.65232300e+03,
        3.46471875e+03,  1.18296875e+03, -8.56234375e+02, -8.28015625e+02,
       -1.83946875e+03,  

In [35]:
target = "SalesPrice" # name of the target variable
y = df[target] # label .. or the target 
X = df.copy() # features ... label is not included
del X[target]
X = pd.get_dummies(X, drop_first=True) # handle catergorical variables ... one hot encoding

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                            , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=5, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.SGDRegressor(alpha=0.7, max_iter= 1000
                                      , l1_ratio=1.0, random_state=1))
])
                                      
pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("Training mse:", metrics.mean_squared_error(y_train, y_train_pred),
     "\nTest mse:", metrics.mean_squared_error(y_test, y_test_pred), 
      "\nTraining r2:", metrics.r2_score(y_train, y_train_pred),
      "\nTest r2:", metrics.r2_score(y_test, y_test_pred))

pipe.steps[-1][-1].coef_

Training mse: 827118590.9069798 
Test mse: 1253685354.2374074 
Training r2: 0.8609575338359388 
Test r2: 0.8244212626030153


array([-2177.28035   ,  -354.77586856,  2961.62873378,  7271.64981794,
        2611.32054621,  1412.18497543,  2498.98354766,  3648.17013011,
        1823.96139715,   771.3586944 ,   332.6842698 ,  2494.62119926,
        3944.70214884,  3367.05443571,   451.81964773,  5728.77277158,
        1308.07973683,   117.00881063,  3585.75904724,  2009.82152198,
         739.28328404, -1693.82560095,  4737.69011143,  2724.11044106,
         760.25002147,  4459.19586513,  3588.99968301,  2253.52292784,
        1205.61053035,   468.20743158,   416.34410986,  1557.47906058,
        -510.113726  ,    66.60186102,  -291.66447942,   -50.29882529,
         366.21179123,   270.65653241,  1388.79839911, -1469.27482628,
         254.12738599,    13.44641726,   668.48472994,  1345.60567345,
       -2104.04127098,  -655.69049721,  1505.22478501,  -426.1862924 ,
        1961.94814032,  1416.85829069,  -667.41576524,  -295.95219471,
        -500.11397106,  1243.0782286 ,    30.84213431,   -72.52480448,
      

In [54]:
target = "SalesPrice" # name of the target variable
y = df[target] # label .. or the target 
X = df.copy() # features ... label is not included
del X[target]
X = pd.get_dummies(X, drop_first=True) # handle catergorical variables ... one hot encoding

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y
                            , test_size = 0.3, random_state = 174298)

pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=5, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.Lasso(alpha=350.0, max_iter= 10000
                                      , random_state=1))
])
                                      
pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("Training mse:", metrics.mean_squared_error(y_train, y_train_pred),
     "\nTest mse:", metrics.mean_squared_error(y_test, y_test_pred), 
      "\nTraining r2:", metrics.r2_score(y_train, y_train_pred),
      "\nTest r2:", metrics.r2_score(y_test, y_test_pred))

pipe.steps[-1][-1].coef_

Training mse: 439657815.15857494 
Test mse: 1007194927.329995 
Training r2: 0.930061477665498 
Test r2: 0.8411388473844681


array([-4.08373157e+03, -1.31570972e+02,  3.82924519e+03,  1.16002612e+04,
        5.02602131e+03,  7.73207137e+03,  2.13878173e+03,  5.27893399e+03,
        3.96597862e+03,  2.51330110e+02, -0.00000000e+00,  2.93115712e+03,
        0.00000000e+00,  0.00000000e+00, -1.48232532e+03,  2.60060032e+04,
        2.93960204e+03,  7.92280664e+02,  3.09636709e+03,  6.28552159e+02,
       -3.07004865e+03, -2.62077927e+03,  3.77345839e+03,  1.60182589e+03,
        0.00000000e+00,  2.75824692e+03,  2.27312531e+03,  1.66549284e+03,
        5.43376198e+02,  0.00000000e+00,  6.45827697e+02,  1.76762678e+03,
        1.64514740e+04, -0.00000000e+00, -1.93388518e+02,  0.00000000e+00,
        0.00000000e+00, -3.67976873e+02,  0.00000000e+00, -2.07849618e+03,
        8.88619868e+02,  2.28105758e+02, -0.00000000e+00,  5.95975093e+02,
       -1.23412768e+03,  0.00000000e+00,  8.07389842e+02, -5.68610165e+02,
        5.44470990e+01,  2.29297385e+03, -9.47991559e+02, -8.29117503e+00,
        0.00000000e+00,  

In [46]:
result = pd.DataFrame({"feature": X.columns, "coef": pipe.steps[-1][-1].coef_})

In [52]:
X.shape

(1460, 258)

In [49]:
result["abs_coef"] = np.abs(result.coef)

In [53]:
pd.options.display.max_rows = 100
result.sort_values("abs_coef", ascending = False).query("abs_coef > 0")

coef               feature      abs_coef
110  3.133547e+04      RoofMatl_CompShg  3.133547e+04
15   2.302975e+04             GrLivArea  2.302975e+04
114  2.110022e+04      RoofMatl_Tar&Grv  2.110022e+04
116  2.073417e+04      RoofMatl_WdShngl  2.073417e+04
3    1.145134e+04           OverallQual  1.145134e+04
115  1.126222e+04      RoofMatl_WdShake  1.126222e+04
151 -1.077270e+04          ExterQual_TA  1.077270e+04
200 -9.082749e+03        KitchenQual_Gd  9.082749e+03
201 -8.965792e+03        KitchenQual_TA  8.965792e+03
150 -8.706709e+03          ExterQual_Gd  8.706709e+03
70   8.630464e+03  Neighborhood_NridgHt  8.630464e+03
111  7.879397e+03      RoofMatl_Membran  7.879397e+03
76   7.737231e+03  Neighborhood_StoneBr  7.737231e+03
90  -7.537593e+03       Condition2_PosN  7.537593e+03
113  6.675205e+03         RoofMatl_Roll  6.675205e+03
5    6.592202e+03             YearBuilt  6.592202e+03
25   6.370007e+03            GarageCars  6.370007e+03
250  5.861238e+03          SaleType_New  5.861238e+03
169  5.555420e+03       BsmtExposure_Gd  5.555420e+03
2    5.455954e+03               LotArea  5.455954e+03
4    5.353874e+03           OverallCond  5.353874e+03
69   4.986192e+03  Neighborhood_NoRidge  4.986192e+03
162 -4.685558e+03           BsmtQual_Gd  4.685558e+03
60   4.607070e+03  Neighborhood_Crawfor  4.607070e+03
8    4.479666e+03            BsmtFinSF1  4.479666e+03
48   4.181225e+03       LandContour_Lvl  4.181225e+03
0   -3.928132e+03            MSSubClass  3.928132e+03
97  -3.361397e+03       BldgType_TwnhsE  3.361397e+03
22   3.298352e+03          TotRmsAbvGrd  3.298352e+03
171 -3.038160e+03       BsmtExposure_No  3.038160e+03
164 -2.958424e+03           BsmtQual_TA  2.958424e+03
32   2.928067e+03              PoolArea  2.928067e+03
23   2.849018e+03            Fireplaces  2.849018e+03
7    2.842850e+03            MasVnrArea  2.842850e+03
80   2.789019e+03       Condition1_Norm  2.789019e+03
46   2.498724e+03       LandContour_HLS  2.498724e+03
236  2.441067e+03           PoolQC_None  2.441067e+03
61  -2.332323e+03  Neighborhood_Edwards  2.332323e+03
96  -2.306516e+03        BldgType_Twnhs  2.306516e+03
235 -2.276739e+03             PoolQC_Gd  2.276739e+03
18   2.200103e+03              FullBath  2.200103e+03
21  -2.156071e+03          KitchenAbvGr  2.156071e+03
174  2.140962e+03      BsmtFinType1_GLQ  2.140962e+03
26   2.118205e+03            GarageArea  2.118205e+03
207  2.104125e+03        Functional_Typ  2.104125e+03
172 -2.048628e+03     BsmtExposure_None  2.048628e+03
119  2.041222e+03   Exterior1st_BrkFace  2.041222e+03
95  -1.898752e+03       BldgType_Duplex  1.898752e+03
27   1.845626e+03            WoodDeckSF  1.845626e+03
49   1.843088e+03     LotConfig_CulDSac  1.843088e+03
..            ...                   ...           ...
145 -5.088719e+02   Exterior2nd_Wd Shng  5.088719e+02
143  4.917238e+02   Exterior2nd_VinylSd  4.917238e+02
118 -4.661355e+02   Exterior1st_BrkComm  4.661355e+02
19   4.635075e+02              HalfBath  4.635075e+02
232 -4.631779e+02          PavedDrive_P  4.631779e+02
78   4.438151e+02  Neighborhood_Veenker  4.438151e+02
51  -4.433850e+02         LotConfig_FR3  4.433850e+02
160 -4.384954e+02       Foundation_Wood  4.384954e+02
52  -4.294243e+02      LotConfig_Inside  4.294243e+02
212 -4.017828e+02        FireplaceQu_TA  4.017828e+02
189  3.868823e+02          Heating_Wall  3.868823e+02
198 -3.848061e+02      Electrical_SBrkr  3.848061e+02
47  -3.766607e+02       LandContour_Low  3.766607e+02
181 -3.749758e+02      BsmtFinType2_LwQ  3.749758e+02
211  3.672505e+02        FireplaceQu_Po  3.672505e+02
67   3.649264e+02  Neighborhood_NPkVill  3.649264e+02
84   3.594728e+02       Condition1_RRAn  3.594728e+02
170 -3.372467e+02       BsmtExposure_Mn  3.372467e+02
14  -3.192158e+02          LowQualFinSF  3.192158e+02
146 -2.895257e+02    MasVnrType_BrkFace  2.895257e+02
142 -2.838364e+02    Exterior2nd_Stucco  2.838364e+02
106  2.671562e+02     RoofStyle_Gambrel  2.671562e+02
29   2.622470e+02

In [56]:
scores = model_selection.cross_val_score(pipe, X_train, y_train
                        , cv = 5, scoring="r2")
scores

array([0.85904276, 0.83727278, 0.2906562 , 0.49587677, 0.883775  ])

In [57]:
np.mean(scores)

0.6733247003814786

In [66]:
pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=5, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.SGDRegressor(max_iter= 1000,
                                      random_state=1))
])

param_grid = {
    "est__alpha": [10.0, 100.0, 500.0, 600, 700, 1000],
    "est__l1_ratio": np.linspace(0, 1, 10)
}
grid_search = model_selection.GridSearchCV(pipe, param_grid, 
                                cv=5, scoring="r2")
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=1000, n_iter=None, penalty='l2',
       power_t=0.25, random_state=1, shuffle=True, tol=None, verbose=0,
       warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'est__alpha': [10.0, 100.0, 500.0, 600, 700, 1000], 'est__l1_ratio': array([0.     , 0.11111, 0.22222, 0.33333, 0.44444, 0.55556, 0.66667,
       0.77778, 0.88889, 1.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)

In [67]:
grid_search.best_params_

{'est__alpha': 10.0, 'est__l1_ratio': 0.0}

In [68]:
grid_search.best_score_

0.6164437794824362

In [69]:
grid_search.best_estimator_

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', SGDRegressor(alpha=10.0, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.0, learning_rate='invscaling',
       loss='squared_loss', max_iter=1000, n_iter=None, penalty='l2',
       power_t=0.25, random_state=1, shuffle=True, tol=None, verbose=0,
       warm_start=False))])