In [1]:
import pandas as pd
from sklearn import *
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv("/data/credit-default.csv")
df.head()

checking_balance  months_loan_duration credit_history    purpose  amount  \
0           < 0 DM                     6       critical   radio/tv    1169   
1       1 - 200 DM                    48         repaid   radio/tv    5951   
2          unknown                    12       critical  education    2096   
3           < 0 DM                    42         repaid  furniture    7882   
4           < 0 DM                    24        delayed  car (new)    4870   

  savings_balance employment_length  installment_rate personal_status  \
0         unknown           > 7 yrs                 4     single male   
1        < 100 DM         1 - 4 yrs                 2          female   
2        < 100 DM         4 - 7 yrs                 2     single male   
3        < 100 DM         4 - 7 yrs                 2     single male   
4        < 100 DM         1 - 4 yrs                 3     single male   

  other_debtors         ...                          property age  \
0          none         ...                       real estate  67   
1          none         ...                       real estate  22   
2          none         ...                       real estate  49   
3     guarantor         ...          building society savings  45   
4          none         ...                      unknown/none  53   

   installment_plan   housing existing_credits  default  dependents  \
0              none       own                2        1           1   
1              none       own                1        2           1   
2              none       own                1        1           2   
3              none  for free                1        1           2   
4              none  for free                2        2           2   

   telephone foreign_worker                 job  
0        yes            yes    skilled employee  
1       none            yes    skilled employee  
2       none            yes  unskilled resident  
3       none            yes    skilled employee  
4       none            yes    skilled employee  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
checking_balance        1000 non-null object
months_loan_duration    1000 non-null int64
credit_history          1000 non-null object
purpose                 1000 non-null object
amount                  1000 non-null int64
savings_balance         1000 non-null object
employment_length       1000 non-null object
installment_rate        1000 non-null int64
personal_status         1000 non-null object
other_debtors           1000 non-null object
residence_history       1000 non-null int64
property                1000 non-null object
age                     1000 non-null int64
installment_plan        1000 non-null object
housing                 1000 non-null object
existing_credits        1000 non-null int64
default                 1000 non-null int64
dependents              1000 non-null int64
telephone               1000 non-null object
foreign_worker          1000 non-null object
jo

In [5]:
y.value_counts()

1    700
2    300
Name: default, dtype: int64

In [16]:
target = "default"
X = df.drop(columns=target)

label_encoder = preprocessing.LabelEncoder()

y = label_encoder.fit_transform(df[target])

X = pd.get_dummies(X, drop_first=True)
features = X.columns

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y
                                            , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=1, include_bias=False)),
    #("scaler", preprocessing.StandardScaler()),
    ("est", tree.DecisionTreeClassifier(max_depth =3, random_state = 1
                                        , min_impurity_decrease = 0.001, min_samples_leaf = 10))
])

pipe.fit(X_train, y_train)

# Class prediction
y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

# Probability estimate
y_train_prob = pipe.predict_proba(X_train)[:, 1]
y_test_prob = pipe.predict_proba(X_test)[:, 1]

print("Confusion matrix: \n", metrics.confusion_matrix(y_test, y_test_pred))



print("Training accuracy:", metrics.accuracy_score(y_train, y_train_pred))
print("Test accuracy:", metrics.accuracy_score(y_test, y_test_pred))

print("Training precision:", metrics.precision_score(y_train, y_train_pred))
print("Test precision:", metrics.precision_score(y_test, y_test_pred))

print("Training recall:", metrics.recall_score(y_train, y_train_pred))
print("Test recall:", metrics.recall_score(y_test, y_test_pred))

Confusion matrix: 
 [[193  21]
 [ 57  29]]
Training accuracy: 0.7471428571428571
Test accuracy: 0.74
Training precision: 0.6412213740458015
Test precision: 0.58
Training recall: 0.3925233644859813
Test recall: 0.3372093023255814


In [13]:
est = pipe.steps[-1][-1]

In [22]:
from sklearn.tree import export_graphviz
export_graphviz(est, out_file = "tree.dot", feature_names = X.columns, filled=True)
!dot -Tpng tree.dot -o tree.png


In [17]:
scores = model_selection.cross_val_score(pipe, X, y, cv = 5)
scores, np.mean(scores)

(array([0.75 , 0.695, 0.715, 0.695, 0.69 ]), 0.7089999999999999)

In [21]:
est = pipe.steps[-1][-1]
summary = pd.DataFrame({"importance": est.feature_importances_, "feature": features})
summary.sort_values("importance", ascending = False)

importance                                feature
9     0.533473               checking_balance_unknown
0     0.183929                   months_loan_duration
24    0.086350               savings_balance_< 100 DM
11    0.085644            credit_history_fully repaid
39    0.060633                  installment_plan_none
35    0.027046                     other_debtors_none
27    0.022925            employment_length_1 - 4 yrs
36    0.000000                         property_other
28    0.000000            employment_length_4 - 7 yrs
29    0.000000              employment_length_> 7 yrs
30    0.000000           employment_length_unemployed
31    0.000000                 personal_status_female
32    0.000000           personal_status_married male
33    0.000000            personal_status_single male
34    0.000000                other_debtors_guarantor
3     0.000000                      residence_history
37    0.000000                   property_real estate
26    0.000000                savings_balance_unknown
40    0.000000                installment_plan_stores
41    0.000000                            housing_own
42    0.000000                           housing_rent
43    0.000000                          telephone_yes
44    0.000000                     foreign_worker_yes
45    0.000000                   job_skilled employee
46    0.000000            job_unemployed non-resident
38    0.000000                  property_unknown/none
25    0.000000              savings_balance_> 1000 DM
4     0.000000                                    age
14    0.000000                      purpose_car (new)
5     0.000000                       existing_credits
6     0.000000                             dependents
7     0.000000                checking_balance_< 0 DM
8     0.000000              checking_balance_> 200 DM
2     0.000000                       installment_rate
10    0.000000                 credit_history_delayed
12    0.000000  credit_history_fully repaid this bank
13    0.000000                  credit_history_repaid
15    0.000000                     purpose_car (used)
1     0.000000                                 amount
16    0.000000            purpose_domestic appliances
17    0.000000                      purpose_education
18    0.000000                      purpose_furniture
19    0.000000                         purpose_others
20    0.000000                       purpose_radio/tv
21    0.000000                        purpose_repairs
22    0.000000                     purpose_retraining
23    0.000000          savings_balance_501 - 1000 DM
47    0.000000                 job_unskilled resident

In [34]:
target = "default"
X = df.drop(columns=target)

label_encoder = preprocessing.LabelEncoder()

y = label_encoder.fit_transform(df[target])

X = pd.get_dummies(X, drop_first=True)
features = X.columns

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y
                                            , test_size = 0.3, random_state = 1)

pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=1, include_bias=False)),
    #("scaler", preprocessing.StandardScaler()),
    ("est", ensemble.RandomForestClassifier(n_estimators = 50, max_features= 0.5,  max_depth =10, random_state = 1
                                        , min_samples_leaf = 5))
])

pipe.fit(X_train, y_train)

# Class prediction
y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

# Probability estimate
y_train_prob = pipe.predict_proba(X_train)[:, 1]
y_test_prob = pipe.predict_proba(X_test)[:, 1]

print("Confusion matrix: \n", metrics.confusion_matrix(y_test, y_test_pred))



print("Training accuracy:", metrics.accuracy_score(y_train, y_train_pred))
print("Test accuracy:", metrics.accuracy_score(y_test, y_test_pred))

print("Training precision:", metrics.precision_score(y_train, y_train_pred))
print("Test precision:", metrics.precision_score(y_test, y_test_pred))

print("Training recall:", metrics.recall_score(y_train, y_train_pred))
print("Test recall:", metrics.recall_score(y_test, y_test_pred))

Confusion matrix: 
 [[193  21]
 [ 52  34]]
Training accuracy: 0.8957142857142857
Test accuracy: 0.7566666666666667
Training precision: 0.9433962264150944
Test precision: 0.6181818181818182
Training recall: 0.7009345794392523
Test recall: 0.3953488372093023


In [35]:
est = pipe.steps[-1][-1]
summary = pd.DataFrame({"importance": est.feature_importances_, "feature": features})
summary.sort_values("importance", ascending = False)

importance                                feature
1     0.176181                                 amount
9     0.123503               checking_balance_unknown
0     0.120579                   months_loan_duration
4     0.090566                                    age
7     0.065790                checking_balance_< 0 DM
2     0.050901                       installment_rate
3     0.036436                      residence_history
14    0.026135                      purpose_car (new)
39    0.024140                  installment_plan_none
43    0.018639                          telephone_yes
24    0.018307               savings_balance_< 100 DM
13    0.016817                  credit_history_repaid
11    0.016721            credit_history_fully repaid
45    0.016182                   job_skilled employee
37    0.013179                   property_real estate
26    0.013051                savings_balance_unknown
20    0.012786                       purpose_radio/tv
33    0.011338            personal_status_single male
41    0.010677                            housing_own
35    0.010581                     other_debtors_none
31    0.010360                 personal_status_female
5     0.009864                       existing_credits
29    0.009817              employment_length_> 7 yrs
15    0.009713                     purpose_car (used)
27    0.009395            employment_length_1 - 4 yrs
18    0.008502                      purpose_furniture
42    0.007162                           housing_rent
36    0.006905                         property_other
34    0.006691                other_debtors_guarantor
10    0.006605                 credit_history_delayed
28    0.006128            employment_length_4 - 7 yrs
12    0.005381  credit_history_fully repaid this bank
38    0.004746                  property_unknown/none
8     0.004589              checking_balance_> 200 DM
40    0.004072                installment_plan_stores
6     0.004019                             dependents
30    0.003995           employment_length_unemployed
25    0.003198              savings_balance_> 1000 DM
47    0.003113                 job_unskilled resident
32    0.001592           personal_status_married male
21    0.000569                        purpose_repairs
19    0.000410                         purpose_others
17    0.000374                      purpose_education
44    0.000281                     foreign_worker_yes
23    0.000012          savings_balance_501 - 1000 DM
16    0.000000            purpose_domestic appliances
22    0.000000                     purpose_retraining
46    0.000000            job_unemployed non-resident

In [36]:
est.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
             max_features=0.5, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=5, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1791095845, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
             max_features=0.5, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=5, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2135392491, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
             max_features=0.5, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=5, min_samples_split=2,
             min_weight_fraction_l