In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/data/bank-full.csv", sep = ";")

In [3]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [4]:
df.shape

(45211, 17)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
age          45211 non-null int64
job          45211 non-null object
marital      45211 non-null object
education    45211 non-null object
default      45211 non-null object
balance      45211 non-null int64
housing      45211 non-null object
loan         45211 non-null object
contact      45211 non-null object
day          45211 non-null int64
month        45211 non-null object
duration     45211 non-null int64
campaign     45211 non-null int64
pdays        45211 non-null int64
previous     45211 non-null int64
poutcome     45211 non-null object
y            45211 non-null object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [6]:
from sklearn import preprocessing

In [7]:
label_encoder = preprocessing.LabelEncoder()
y = label_encoder.fit_transform(df.y)
y

array([0, 0, 0, ..., 1, 0, 0])

In [8]:
X = df.drop(columns=["y"])
X.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown

In [9]:
pd.options.display.max_columns = 1000

In [10]:
X_dummy = pd.get_dummies(X)
X_dummy.sample(10)

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
6987    52     -211   28       153         2     -1         0           0   
31755   30     8623    8       163         3     -1         0           0   
7993    48      323    2       230         2     -1         0           0   
11061   58       57   17       117         3     -1         0           0   
30973   42       49    9         7        10     -1         0           0   
19196   36      546    6        91         3     -1         0           0   
42858   34      123    3       301         3     -1         0           0   
33269   35      396   20       110         1     -1         0           0   
34907   51       93    6       221         1     -1         0           0   
9038    40     6536    5       647         1     -1         0           0   

       job_blue-collar  job_entrepreneur  job_housemaid  job_management  \
6987                 1                 0              0               0   
31755                0                 0              0               1   
7993                 1                 0              0               0   
11061                0                 0              1               0   
30973                0                 0              0               0   
19196                0                 0              0               1   
42858                0                 0              0               1   
33269                1                 0              0               0   
34907                0                 0              0               1   
9038                 1                 0              0               0   

       job_retired  job_self-employed  job_services  job_student  \
6987             0                  0             0            0   
31755            0                  0             0            0   
7993             0                  0             0            0   
11061            0                  0             0            0   
30973            0                  0             0            0   
19196            0                  0             0            0   
42858            0                  0             0            0   
33269            0                  0             0            0   
34907            0                  0             0            0   
9038             0                  0             0            0   

       job_technician  job_unemployed  job_unknown  marital_divorced  \
6987                0               0            0                 0   
31755               0               0            0                 0   
7993                0               0            0                 1   
11061               0               0            0                 1   
30973               1               0            0                 0   
19196               0               0            0                 0   
42858               0               0            0                 0   
33269               0               0            0                 0   
34907               0               0            0                 1   
9038                0               0            0                 0   

       marital_married  marital_single  education_primary  \
6987                 1               0                  1   
31755                1               0                  0   
7993                 0               0                  1   
11061                0               0                  1   
30973                0               1                  0   
19196                0               1                  0   
42858                1               0                  0   
33269                1               0                  1   
34907                0               0                  0   
9038                 1               0                  0   

       education_secondary  education_tertiary  education_unknown  default_no  \
6987                     0            

In [11]:
from sklearn import model_selection

In [12]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_dummy, y
                                                    , test_size = 0.3)

In [13]:
X_train.shape

(31647, 51)

In [14]:
X_test.shape

(13564, 51)

In [15]:
len(X_train)/len(X)

0.6999845170423127

In [16]:
from sklearn import linear_model

In [17]:
est = linear_model.LogisticRegression()

In [18]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [19]:
scaling = preprocessing.StandardScaler()
X_train_std = scaling.fit_transform(X_train)
X_test_std = scaling.transform(X_test)

In [20]:
pd.DataFrame(X_train_std).describe()

0             1             2             3             4   \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean  -1.486963e-16  8.206256e-17 -6.601761e-17  1.375193e-17  1.027711e-16   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -2.160374e+00 -3.038324e+00 -1.780021e+00 -9.982031e-01 -5.674448e-01   
25%   -7.463543e-01 -4.194688e-01 -9.374668e-01 -6.024650e-01 -5.674448e-01   
50%   -1.807465e-01 -2.971649e-01  2.545207e-02 -3.027798e-01 -2.444663e-01   
75%    6.676651e-01  2.153688e-02  6.272763e-01  2.274324e-01  7.851213e-02   
max    5.098260e+00  3.139959e+01  1.830925e+00  1.789733e+01  1.945722e+01   

                 5             6             7             8             9   \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean   3.118603e-15  2.376564e-15  1.124627e-15 -9.689991e-16 -3.319899e-16   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -4.118068e-01 -2.360192e-01 -3.614048e-01 -5.213753e-01 -1.846091e-01   
25%   -4.118068e-01 -2.360192e-01 -3.614048e-01 -5.213753e-01 -1.846091e-01   
50%   -4.118068e-01 -2.360192e-01 -3.614048e-01 -5.213753e-01 -1.846091e-01   
75%   -4.118068e-01 -2.360192e-01 -3.614048e-01 -5.213753e-01 -1.846091e-01   
max    8.282237e+00  1.113127e+02  2.766981e+00  1.918004e+00  5.416852e+00   

                 10            11            12            13            14  \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean   1.224083e-15  4.083202e-16 -6.553410e-16  7.955449e-16  1.918426e-15   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -1.652267e-01 -5.138183e-01 -2.277819e-01 -1.896738e-01 -3.187604e-01   
25%   -1.652267e-01 -5.138183e-01 -2.277819e-01 -1.896738e-01 -3.187604e-01   
50%   -1.652267e-01 -5.138183e-01 -2.277819e-01 -1.896738e-01 -3.187604e-01   
75%   -1.652267e-01 -5.138183e-01 -2.277819e-01 -1.896738e-01 -3.187604e-01   
max    6.052289e+00  1.946213e+00  4.390164e+00  5.272208e+00  3.137153e+00   

                 15            16            17            18            19  \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean  -6.193843e-16  5.181111e-16 -2.827846e-16 -3.007008e-17  1.936988e-15   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -1.460555e-01 -4.526715e-01 -1.719666e-01 -8.014933e-02 -3.600623e-01   
25%   -1.460555e-01 -4.526715e-01 -1.719666e-01 -8.014933e-02 -3.600623e-01   
50%   -1.460555e-01 -4.526715e-01 -1.719666e-01 -8.014933e-02 -3.600623e-01   
75%   -1.460555e-01 -4.526715e-01 -1.719666e-01 -8.014933e-02 -3.600623e-01   
max    6.846712e+00  2.209108e+00  5.815082e+00  1.247671e+01  2.777297e+00   

                 20            21            22            23            24  \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean  -5.193039e-16  2.135338e-16  1.008673e-15 -3.984131e-16  1.571004e-15   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -1.233073e+00 -6.266816e-01 -4.216419e-01 -1.028952e+00 -6.453036e-01   
25%   -1.233073e+00 -6.266816e-01 -4.216419e-01 -1.028952e+00 -6.453036e-01   
50%    8.109822e-01 -6.266816e-01 -4.216419e-01  9.718622e-01 -6.453036e-01   
75%    8.109822e-01  1.595707e+00 -4.216419e-01  9.718622e-01  1.549658e+00   
max    8.109822e-01  1.595707e+00  2.371681e+00  9.718622e-01  1.549658e+00   

                 25            26            27            28            29  \
count  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04  3.164700e+04   
mean   2.400531e-15 -1.350691e-15 -3.830422e-16  1.540988e-15 -1.514284e-15   
std    1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00  1.000016e+00   
min   -2.062248e-01 -7.471069e+00 -1.338496e-01 -8.893258e-01 -1.124447e+00   
25%   -2.062248e-01  1.338496e-01 -1.338496e-01 -8.893258e-01 

In [21]:
est.fit(X_train_std, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
y_train_pred = est.predict(X_train_std)
y_test_pred = est.predict(X_test_std)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
pd.DataFrame({"actual": y_train, "predicted": y_train_pred}).sample(10)

actual  predicted
30598       0          0
18649       0          0
17659       0          0
4197        0          0
24126       0          0
13619       0          0
3523        0          0
2569        0          0
17247       0          0
26850       0          0

In [24]:
from sklearn import metrics

In [25]:
metrics.accuracy_score(y_train, y_train_pred)

0.9006540904351124

In [26]:
metrics.accuracy_score(y_test, y_test_pred)

0.9040106163373636

In [27]:
pd.Series(y_train).value_counts()/len(y_train)

0    0.882201
1    0.117799
dtype: float64

In [28]:
pd.Series(y_test).value_counts()/len(y_test)

0    0.884916
1    0.115084
dtype: float64

In [29]:
metrics.confusion_matrix(y_test, y_test_pred)

array([[11729,   274],
       [ 1028,   533]])

In [30]:
y_test_prob = est.predict_proba(X_test_std)
y_test_prob.shape

(13564, 2)

In [31]:
y_test_prob[:, 1]

array([0.01476308, 0.044927  , 0.03110607, ..., 0.00883398, 0.08715678,
       0.00852171])

In [32]:
len(y_test_prob[:, 1])

13564

In [33]:
import numpy as np

In [34]:
y_test_pred = np.where(y_test_prob[:, 1] > 0.5, 1, 0)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))


[[11729   274]
 [ 1028   533]]
0.9040106163373636


In [35]:
y_test_pred = np.where(y_test_prob[:, 1] > 0.8, 1, 0)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

[[11929    74]
 [ 1352   209]]
0.8948687702742554


In [36]:
y_test_pred = np.where(y_test_prob[:, 1] > 0.1, 1, 0)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

[[9691 2312]
 [ 221 1340]]
0.8132556767915069


In [37]:
est.coef_

array([[-1.14266680e-02,  4.17581663e-02,  9.41462241e-02,
         1.07876320e+00, -3.10013453e-01, -2.75936994e-03,
         1.61549272e-02,  5.88382111e-02, -5.55500307e-02,
        -2.55065869e-02, -8.65756577e-02,  8.78678536e-03,
         9.71065731e-02, -2.76866515e-02, -8.13281117e-03,
         9.25364061e-02, -1.98432785e-02,  1.97922447e-04,
        -6.86204308e-03,  6.46654508e-03, -6.10242364e-02,
         6.17676309e-02, -5.79120766e-02, -1.59412585e-02,
         6.04619708e-02,  5.83338171e-03,  7.21431231e-03,
        -7.21431231e-03,  1.74490374e-01, -1.74490374e-01,
         8.09431584e-02, -8.09431584e-02,  3.17419353e-01,
         1.20594292e-01, -4.00780110e-01,  8.57675649e-02,
        -1.10716976e-01,  7.61017203e-02,  6.83279575e-02,
        -1.45181532e-01, -1.65715374e-01,  2.72260400e-01,
         1.87323269e-01, -3.75403186e-02, -1.53571608e-01,
         1.54148207e-01,  1.36420425e-01, -6.01129081e-02,
         5.29957642e-03,  3.60476112e-01, -1.22876565e-0

In [38]:
pd.DataFrame({"feature": X_train.columns, "coefficient": est.coef_[0,:]})

feature  coefficient
0                   age    -0.011427
1               balance     0.041758
2                   day     0.094146
3              duration     1.078763
4              campaign    -0.310013
5                 pdays    -0.002759
6              previous     0.016155
7            job_admin.     0.058838
8       job_blue-collar    -0.055550
9      job_entrepreneur    -0.025507
10        job_housemaid    -0.086576
11       job_management     0.008787
12          job_retired     0.097107
13    job_self-employed    -0.027687
14         job_services    -0.008133
15          job_student     0.092536
16       job_technician    -0.019843
17       job_unemployed     0.000198
18          job_unknown    -0.006862
19     marital_divorced     0.006467
20      marital_married    -0.061024
21       marital_single     0.061768
22    education_primary    -0.057912
23  education_secondary    -0.015941
24   education_tertiary     0.060462
25    education_unknown     0.005833
26           default_no     0.007214
27          default_yes    -0.007214
28           housing_no     0.174490
29          housing_yes    -0.174490
30              loan_no     0.080943
31             loan_yes    -0.080943
32     contact_cellular     0.317419
33    contact_telephone     0.120594
34      contact_unknown    -0.400780
35            month_apr     0.085768
36            month_aug    -0.110717
37            month_dec     0.076102
38            month_feb     0.068328
39            month_jan    -0.145182
40            month_jul    -0.165715
41            month_jun     0.272260
42            month_mar     0.187323
43            month_may    -0.037540
44            month_nov    -0.153572
45            month_oct     0.154148
46            month_sep     0.136420
47     poutcome_failure    -0.060113
48       poutcome_other     0.005300
49     poutcome_success     0.360476
50     poutcome_unknown    -0.122877

In [39]:
from sklearn import pipeline

In [40]:
pipe = pipeline.Pipeline([
    #("poly", preprocessing.PolynomialFeatures(degree=2
        #, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est", linear_model.LogisticRegression(C = 10.0))
])

pipe.fit(X_train, y_train)
y_test_pred = pipe.predict(X_test)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

[[11729   274]
 [ 1028   533]]
0.9040106163373636


In [41]:
a = np.array([
    [1, 2, 3],
    [2, 2, 2],
    [-1, 0, 1],
    [3, 4, 5]
])
a

array([[ 1,  2,  3],
       [ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  4,  5]])

In [42]:
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(a)

array([[ 1.,  2.,  3.,  1.,  2.,  3.,  4.,  6.,  9.],
       [ 2.,  2.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [-1.,  0.,  1.,  1., -0., -1.,  0.,  0.,  1.],
       [ 3.,  4.,  5.,  9., 12., 15., 16., 20., 25.]])

In [43]:
linear_model.LogisticRegression?

In [44]:
from sklearn import tree

In [60]:
est = tree.DecisionTreeClassifier(max_depth=6, max_leaf_nodes=20)
est.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=20,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [61]:
y_test_pred = est.predict(X_test)

In [62]:
y_test_pred = est.predict(X_test)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

[[11648   355]
 [  931   630]]
0.9051902093777646


In [63]:
from sklearn.tree import export_graphviz
export_graphviz(est, out_file = "tree.dot", feature_names = X_train.columns, filled=True)
!dot -Tpng tree.dot -o tree.png

In [64]:
summary = pd.DataFrame({"feature": X_train.columns
              , "importance":est.feature_importances_ }) 
summary.sort_values("importance", ascending = False
                   )

feature  importance
3              duration    0.545803
49     poutcome_success    0.280669
29          housing_yes    0.045901
34      contact_unknown    0.035845
42            month_mar    0.022199
35            month_apr    0.019069
41            month_jun    0.018080
5                 pdays    0.015636
45            month_oct    0.011166
46            month_sep    0.005631
0                   age    0.000000
36            month_aug    0.000000
30              loan_no    0.000000
31             loan_yes    0.000000
32     contact_cellular    0.000000
33    contact_telephone    0.000000
40            month_jul    0.000000
37            month_dec    0.000000
38            month_feb    0.000000
39            month_jan    0.000000
27          default_yes    0.000000
43            month_may    0.000000
44            month_nov    0.000000
47     poutcome_failure    0.000000
48       poutcome_other    0.000000
28           housing_no    0.000000
25    education_unknown    0.000000
26           default_no    0.000000
1               balance    0.000000
2                   day    0.000000
4              campaign    0.000000
6              previous    0.000000
7            job_admin.    0.000000
8       job_blue-collar    0.000000
9      job_entrepreneur    0.000000
10        job_housemaid    0.000000
11       job_management    0.000000
12          job_retired    0.000000
13    job_self-employed    0.000000
14         job_services    0.000000
15          job_student    0.000000
16       job_technician    0.000000
17       job_unemployed    0.000000
18          job_unknown    0.000000
19     marital_divorced    0.000000
20      marital_married    0.000000
21       marital_single    0.000000
22    education_primary    0.000000
23  education_secondary    0.000000
24   education_tertiary    0.000000
50     poutcome_unknown    0.000000

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
est = RandomForestClassifier(max_depth=6, max_leaf_nodes=20)
est.fit(X_train, y_train)
y_test_pred = est.predict(X_test)
print(metrics.confusion_matrix(y_test, y_test_pred))
print(metrics.accuracy_score(y_test, y_test_pred))

[[11927    76]
 [ 1333   228]]
0.8961220878796815
