In [6]:
import pandas as pd
from sklearn import *

In [4]:
df = pd.read_csv("/data/iris.csv").iloc[:,1:-1]

In [5]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [7]:
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(df.values)

In [12]:
A = X.T

In [9]:
import numpy as np

In [13]:
U, S, VT = np.linalg.svd(A)

In [14]:
U

array([[-0.52237162, -0.37231836,  0.72101681,  0.26199559],
       [ 0.26335492, -0.92555649, -0.24203288, -0.12413481],
       [-0.58125401, -0.02109478, -0.14089226, -0.80115427],
       [-0.56561105, -0.06541577, -0.6338014 ,  0.52354627]])

In [16]:
S/S.sum()

array([0.53427285, 0.30056435, 0.12020858, 0.04495421])

In [18]:
U.std(axis = 0)

array([0.35562414, 0.36085636, 0.49450453, 0.49877793])

In [21]:
A_pca = U.dot(A)

In [23]:
A_pca.shape

(4, 150)

In [24]:
A_pca.std(axis = 1)

array([0.85788356, 0.82232793, 1.45075673, 0.69506653])

In [25]:
from sklearn import decomposition

In [31]:
pca = decomposition.PCA()
X_pca = pca.fit_transform(X)

In [28]:
X_pca.shape

(150, 4)

In [29]:
X_pca.std(axis = 0)

array([1.70611198, 0.95980255, 0.38386622, 0.14355385])

In [30]:
X_pca.std(axis = 0)/X_pca.std(axis = 0).sum()

array([0.53427285, 0.30056435, 0.12020858, 0.04495421])