In [42]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.6.0'

In [9]:
a = tf.constant(2.3)
a

<tf.Tensor 'Const_3:0' shape=() dtype=float32>

In [10]:
b = tf.constant(3.4)
b

<tf.Tensor 'Const_4:0' shape=() dtype=float32>

In [11]:
c = a + b
c

<tf.Tensor 'add_1:0' shape=() dtype=float32>

In [12]:
with tf.Session() as sess:
    c_ = sess.run(c)
    print(c_)

5.7


In [41]:
tf.reset_default_graph()
a = tf.placeholder(dtype=tf.float32, shape=(), name="a")
b = tf.placeholder(dtype=tf.float32, shape=(), name="b")
print("a:", a, "\nb:", b)

c = a + b
print("c:", c)

with tf.Session() as sess:
    c_ = sess.run(c, feed_dict={a: 3.4, b: 2.3})
    print(c_)


a: Tensor("a:0", shape=(), dtype=float32) 
b: Tensor("b:0", shape=(), dtype=float32)
c: Tensor("add:0", shape=(), dtype=float32)
5.7


In [44]:
X_data = np.random.ranf((10, 4))
X_data

array([[0.2218215 , 0.33080264, 0.90506146, 0.81754645],
       [0.16477114, 0.70777903, 0.21215082, 0.88964454],
       [0.45341967, 0.75616083, 0.81574262, 0.54640309],
       [0.59271638, 0.86932407, 0.20830065, 0.84340189],
       [0.56983109, 0.75719139, 0.74323985, 0.99268976],
       [0.34607484, 0.99394657, 0.93786823, 0.21623269],
       [0.75390425, 0.84287561, 0.69695403, 0.14992141],
       [0.58169696, 0.12939281, 0.20638009, 0.16023984],
       [0.02812608, 0.66449123, 0.24479108, 0.12466182],
       [0.52731389, 0.81677366, 0.64103668, 0.02549855]])

In [47]:
W_data = np.random.ranf([4, 1])
W_data

array([[0.7452417 ],
       [0.81015546],
       [0.09259009],
       [0.90885362]])

In [48]:
X_data.dot(W_data)

array([[1.26014198],
       [1.5244051 ],
       [1.52264519],
       [1.93182004],
       [2.00913095],
       [1.34652181],
       [1.44548883],
       [0.70307643],
       [0.6952665 ],
       [1.13721804]])

In [50]:
tf.reset_default_graph()
X = tf.placeholder(dtype=tf.float32, shape=(None, 4), name="a")
W = tf.placeholder(dtype=tf.float32, shape=(4, 1), name="b")
print("X:", X, "\nW:", W)

Z = tf.matmul(X, W)
print("Z:", Z)

with tf.Session() as sess:
    Z_ = sess.run(Z, feed_dict={X: X_data, W: W_data})
    print(Z_)

X: Tensor("a:0", shape=(?, 4), dtype=float32) 
W: Tensor("b:0", shape=(4, 1), dtype=float32)
Z: Tensor("MatMul:0", shape=(?, 1), dtype=float32)
[[1.2601418 ]
 [1.5244051 ]
 [1.5226451 ]
 [1.9318202 ]
 [2.009131  ]
 [1.3465219 ]
 [1.4454888 ]
 [0.7030765 ]
 [0.69526654]
 [1.1372179 ]]
